<a href="https://colab.research.google.com/github/ThunderKing990/Frozenlake/blob/main/Frozen_Lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gym

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install gym[toy_text]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 18.3 MB 177 kB/s 


In [ ]:
!pip install colabgymrender
!apt-get install -y xvfb python-opengl ffmpeg > /dev/null 2>&1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for colabgymrender: filename=colabgymrender-1.1.0-py3-none-any.whl size=3130 sha256=527a2738a898e131799f5eb38c36eda73f0484127ff5c1b0479a9fb09492029c
  Stored in directory: /root/.cache/pip/wheels/e4/d2/e1/cc1c940178ad92438325422b51c3e8c3d927b9ef8381da8840
Successfully built colabgymrender


In [ ]:
!pip install imageio==2.4.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 3.3 MB 4.2 MB/s 
  Created wheel for imageio: filename=imageio-2.4.1-py3-none-any.whl size=3303886 sha256=fdd86e2e58240ed381ad59ebf95cc4a2d9b84384cfce7fc9412458093b321f26
  Stored in directory: /root/.cache/pip/wheels/be/7b/04/4d8d56f1d503e5c404f0de6018c0cfa592c71588a39b49e002
Successfully built imageio
  Attempting uninstall: imageio
    Found existing installation: imageio 2.9.0
    Uninstalling imageio-2.9.0:
      Successfully uninstalled imageio-2.9.0


In [ ]:
import os
os.environ["SDL_VIDEODRIVER"] = "dummy"

In [ ]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output
from colabgymrender.recorder import Recorder

Imageio: 'ffmpeg-linux64-v3.3.1' was not found on your computer; downloading it now.
Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux64-v3.3.1 (43.8 MB)
Downloading: 8192/45929032 bytes (0.0%)2973696/45929032 bytes (6.5%)7151616/45929032 bytes (15.6%)10887168/45929032 bytes (23.7%)14999552/45929032 bytes (32.7%)18964480/45929032 bytes (41.3%)23232512/45929032 bytes (50.6%)27525120/45929032 bytes (59.9%)31211520/45929032 bytes (68.0%)35250176/45929032 bytes (76.7%)39518208/45929032 bytes (86.0%)43835392/45929032 bytes (95.4%)45929032/45929032 bytes (100.0%)
  Done
File saved as /root

In [ ]:
env = gym.make('FrozenLake-v1')
directory = './video'
env = Recorder(env, directory)

  deprecation(

  deprecation(

See here for more information: https://www.gymlibrary.ml/content/api/
  deprecation(



In [ ]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [ ]:
qtable = np.zeros((state_size, action_size))

In [ ]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate= 0.004

In [ ]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()
    done =False
    rewards_current_epsiode = 0
    
    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(qtable[state,:])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        qtable[state, action] = qtable[state, action] * (1- learning_rate) + learning_rate * (reward + discount_rate * np.max(qtable[new_state, :]))

        state = new_state
        rewards_current_epsiode += reward

        if done == True:
          break
    #exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    exploration_rate *= 0.995
    rewards_all_episodes.append(rewards_current_epsiode)

rewards_per_thousand_epsiodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_epsiodes:
  print(f"{count} : {sum(r/1000)}")
  count += 1000

print("\n\n********Q Table********\n")
print(qtable)

********Average reward per thousand episodes********

1000 : 0.20800000000000016
2000 : 0.7060000000000005
3000 : 0.7320000000000005
4000 : 0.7250000000000005
5000 : 0.7330000000000005
6000 : 0.7350000000000005
7000 : 0.7410000000000005
8000 : 0.7040000000000005
9000 : 0.7160000000000005
10000 : 0.7330000000000005


********Q Table********

[[5.52494334e-01 2.62183226e-01 3.33194530e-01 2.83093151e-01]
 [1.13344199e-02 9.61288675e-04 1.84421593e-03 4.67362937e-01]
 [4.20878716e-01 2.89127516e-05 1.68532527e-02 1.98832978e-04]
 [0.00000000e+00 3.26149014e-06 0.00000000e+00 3.98626572e-07]
 [5.69724634e-01 2.53407423e-01 2.73138737e-01 1.61706849e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.94302658e-01 0.00000000e+00 5.67628845e-02 1.85911950e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.76833607e-01 2.48792260e-01 1.20349496e-01 6.32472361e-01]
 [2.17189505e-01 7.00476748e-01 2.54768444e-01 1.32891047e-01]
 [7.15942471e-01 0.00000000

In [ ]:
for episode in range(10):       
    state = env.reset()         
    done = False               
    print("*****EPISODE ", episode+1, "*****\n")            
    for step in range(max_steps_per_episode):   
      action = np.argmax(qtable[state,:])   
      new_state, reward, done, info = env.step(action)  
  
      if done == True :
        if reward == 1:
          print("****You reached the goal!****\n\n")
          env.play()   
          print("#----------------------------#\n\n")
        else:
          print("****You failed to reach the goal!****\n\n")
          env.play()     
          print("#----------------------------#\n\n")

        break
      state = new_state    
env.close()  

  result = np.fromstring(s, dtype='uint8')



*****EPISODE  1 *****

****You reached the goal!****




  warnings.warn("Warning: in file %s, "%(self.filename)+



#----------------------------#


*****EPISODE  2 *****

****You reached the goal!****




  warnings.warn("Warning: in file %s, "%(self.filename)+



#----------------------------#


*****EPISODE  3 *****

****You reached the goal!****




#----------------------------#


*****EPISODE  4 *****

****You reached the goal!****




#----------------------------#


*****EPISODE  5 *****

****You reached the goal!****




#----------------------------#


*****EPISODE  6 *****

****You reached the goal!****




#----------------------------#


*****EPISODE  7 *****

****You reached the goal!****




  warnings.warn("Warning: in file %s, "%(self.filename)+



#----------------------------#


*****EPISODE  8 *****

****You failed to reach the goal!****




#----------------------------#


*****EPISODE  9 *****

****You reached the goal!****




#----------------------------#


*****EPISODE  10 *****

****You reached the goal!****




#----------------------------#


